import { useEffect,useState } from 'react';
import snapshot from '../data/generated/unified-data.json';
import type { UnifiedTFTData,Comp,CompSourceData,SourceStatus,Freshness,Provenance } from '../types/terminal';
import { sourceNames,archetypeNames } from '../types/terminal';
import { sourceFreshness } from '../utils/sourceFreshness';
import '../terminal.css';
import {useCacheState,cacheLabels,applyCacheUpdate} from '../utils/pwa';
const entityLabels:Record<string,string>={silver:'银色',gold:'金色',prismatic:'棱彩',component:'散件',completed:'成装',radiant:'光明',artifact:'神器',emblem:'纹章',consumable:'消耗品',tactician:'人口装备'};
const data=snapshot as UnifiedTFTData;
const labels:Record<Freshness,string>={fresh:'已同步',stale:'版本滞后 / 数据较旧',unknown:'待确认',error:'采集异常'};
const fmt=(s?:string)=>s?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'未提供';
const ago=(s:string)=>{const m=Math.max(0,Math.floor((Date.now()-Date.parse(s))/60000));return m<1?'刚刚':m<60?`${m}分钟前`:m<1440?`${Math.floor(m/60)}小时前`:`${Math.floor(m/1440)}天前`;};
const names=new Map(data.champions.map(c=>[c.id,c.name]));const traits=new Map(data.traits.map(c=>[c.id,c.name]));
function Badge({status}:{status:Freshness}){return <span className={`t-badge ${status}`}>{labels[status]}</span>;}
function state(s:CompSourceData):Freshness {if(s.retentionReason==='error'||data.sourceStatus.find(p=>p.id===s.source)?.status==='error')return 'error';if(s.retained&&s.patch===data.metadata.patch)return 'unknown';return sourceFreshness(s.patch,data.metadata.patch,s.collectedAt,Date.now(),s.sourceUpdatedAt);}
function Icon({name,src}:{name:string;src?:string}){const[failed,setFailed]=useState(false);return <span className="t-icon">{src&&!failed?<img src={src} alt="" loading="lazy" onError={()=>setFailed(true)}/>:name.slice(0,1)}</span>;}
function SourceLine({s,detail=false}:{s:CompSourceData;detail?:boolean}){return <div className="t-source-line"><div><a href={s.sourceUrl} target="_blank" rel="noreferrer">{sourceNames[s.source]} ↗</a><strong>{s.tier??(s.category?`分组 ${s.category}`:undefined)??(s.avgPlacement!==undefined?`均排 ${s.avgPlacement.toFixed(2)}`:'暂无评级')}</strong></div><small>Patch {s.patch} · {ago(s.collectedAt)} {state(s)!=='fresh'&&<Badge status={state(s)}/>} {s.retained&&<span>保留快照 · {s.retentionReason==='error'?'本次采集失败':s.retentionReason==='missing'?'本次未收录':'历史版本'}</span>}</small>{detail&&<><div className="t-stats">{s.tier&&<span>评级 {s.tier}</span>}{s.avgPlacement!==undefined&&<span>均排 {s.avgPlacement.toFixed(2)}</span>}{s.top4Rate!==undefined&&<span>前四 {(s.top4Rate*100).toFixed(1)}%</span>}{s.winRate!==undefined&&<span>胜率 {(s.winRate*100).toFixed(1)}%</span>}{s.playRate!==undefined&&<span>登场 {(s.playRate*100).toFixed(2)}%</span>}{s.sampleSize!==undefined&&<span>样本 {s.sampleSize.toLocaleString()}</span>}{s.trendDelta!==undefined&&<span>原站均排变化 {s.trendDelta>0?'+':''}{s.trendDelta.toFixed(3)}</span>}{s.trend&&<span>原站趋势 {s.trend}</span>}</div><p>采集 {fmt(s.collectedAt)} · 来源更新 {fmt(s.sourceUpdatedAt)}</p>{s.notes.map(n=><p key={n}>{n}</p>)}</>}</div>;}
function CompRow({comp}:{comp:Comp}){return <article className="t-comp"><a className="t-comp-name" href={`#/comps/${comp.id}`}><h3>{comp.name}</h3><span>›</span></a><p className="t-meta">{archetypeNames[comp.archetype]}{comp.carries.length?' · '+comp.carries.map(id=>names.get(id)??id).join(' / '):''}</p><div className="t-rating-grid">{comp.sources.filter(s=>s.patch===data.metadata.patch).concat(comp.sources.filter(s=>s.patch!==data.metadata.patch)).slice(0,3).map(s=><SourceLine key={s.source+s.sourceRecordId+s.patch} s={s}/>)}</div></article>;}
function SourceRow({s}:{s:SourceStatus}){const status=s.status==='error'?'error':sourceFreshness(s.detectedPatch,data.metadata.patch,s.collectedAt,Date.now(),s.sourceUpdatedAt);return <article className="t-source"><div className="t-between"><a href={s.sourceUrl} target="_blank" rel="noreferrer">{s.name} ↗</a><Badge status={status}/></div><p>Patch {s.detectedPatch??'未识别'} · 采集 {fmt(s.collectedAt)}</p><p>{s.message}</p><details><summary>采集方式与字段</summary><p>{s.method}</p><p>{s.fields.join(' / ')||'暂无可公开展示字段'}</p><p>最近检查 {fmt(s.checkedAt)}{s.sourceUpdatedAt&&` · 来源生成 ${fmt(s.sourceUpdatedAt)}`}</p></details></article>;}
function ProvenanceLine({p}:{p:Provenance}){return <small className="t-provenance"><a href={p.sourceUrl} target="_blank" rel="noreferrer">CommunityDragon ↗</a> · Patch {p.patch} · {fmt(p.collectedAt)}</small>;}
function Catalog({kind}:{kind:'items'|'augments'}){const[q,setQ]=useState('');const[filter,setFilter]=useState('all');const[listCount,setListCount]=useState(30);const list=data[kind];const label=kind==='items'?'装备':'海克斯';const filters:Record<string,string>=kind==='items'?{all:'全部',component:'散件',completed:'成装',artifact:'神器',radiant:'光明',emblem:'纹章'}:{all:'全部',silver:'银色',gold:'金色',prismatic:'棱彩'};
 const shown=list.filter(e=>(e.name+' '+e.id).toLowerCase().includes(q.toLowerCase())&&(filter==='all'||('category'in e?e.category:'tier'in e?e.tier:'')===filter));
 return <><h1>{label}数据 <small>{list.length}</small></h1><label className="t-search">搜索{label}<input value={q} onChange={e=>{setQ(e.target.value);setListCount(30);}} placeholder="搜索名称 / 英文 ID"/></label><div className="t-filters">{Object.entries(filters).map(([id,name])=><button key={id} aria-pressed={filter===id} onClick={()=>{setFilter(id);setListCount(30);}}>{name}</button>)}</div><p className="t-muted">基础信息来自正式 Set。第三方评级与统计尚未接入，空缺不代表表现较弱。</p><div className="t-catalog">{shown.slice(0,listCount).map(e=><article key={e.id}><div className="t-entity-title"><Icon name={e.name} src={e.icon}/><div><h2>{e.name}</h2><small>{'tier'in e?entityLabels[e.tier??'']:'category'in e?entityLabels[e.category??'']:''}</small></div></div><p>{e.description?.replace(/@[^@]+@/g,'〔数值缺失〕')||'来源未提供描述'}</p>{e.description?.includes('@')&&<small>当前来源未提供完整数值，请查看原文。</small>}{'effects'in e&&e.effects&&Object.keys(e.effects).length>0&&<details><summary>基础属性 / 原始参数</summary><dl className="t-effects">{Object.entries(e.effects).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><small>保留原始字段与单位约定；不推算隐藏公式。</small></details>}{kind==='items'&&(!("effects"in e)||!Object.keys(e.effects??{}).length)&&<p className="t-muted">基础属性：当前来源未提供。</p>}<ProvenanceLine p={e.provenance}/><p className="t-muted">来源评级：暂无公开数据</p></article>)}</div>{!shown.length&&<p className="t-empty">没有匹配结果，请换一个名称。</p>}{shown.length>listCount&&<button className="t-more" onClick={()=>setListCount(n=>n+30)}>继续显示（剩余 {shown.length-listCount}）</button>}</>;
}
function CompList(){const[q,setQ]=useState('');const[filter,setFilter]=useState('all');const[old,setOld]=useState(false);const comps=data.comps.filter(c=>(old||c.sources.some(s=>s.patch===data.metadata.patch&&!s.retained))&&(filter==='all'||c.archetype===filter)&&[c.name,...c.aliases,...c.coreUnits.map(id=>names.get(id)??id)].join(' ').toLowerCase().includes(q.toLowerCase()));return <><h1>阵容 <small>{comps.length}</small></h1><label className="t-search">搜索阵容 / 英雄<input placeholder="阵容、中文英雄或英文名称" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="t-filters">{['all','fast8','fast9','reroll1','reroll2','reroll3'].map(f=><button key={f} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f==='all'?'全部':archetypeNames[f as keyof typeof archetypeNames]}</button>)}</div><label className="t-check"><input type="checkbox" checked={old} onChange={e=>setOld(e.target.checked)}/>包含旧版本记录</label><p className="t-muted">按来源收录顺序展示，不计算综合评级；相似名称不一定是同一阵容。</p>{comps.map(c=><CompRow key={c.id} comp={c}/>)}{!comps.length&&<p className="t-empty">没有匹配阵容。</p>}</>;}
function Detail({id}:{id:string}){const c=data.comps.find(c=>c.id===id);if(!c)return <><h1>阵容未找到</h1><a href="#/comps">返回阵容</a></>;const unitList=(title:string,ids:string[])=> <section className="t-section"><h2>{title}</h2>{ids.length?<div className="t-units">{ids.map(id=>{const u=data.champions.find(x=>x.id===id);return <span key={id}><Icon name={u?.name??id} src={u?.icon}/>{u?.name??id}{u&&<small>{u.cost}费</small>}</span>;})}</div>:<p className="t-muted">来源未明确提供，暂不推断。</p>}</section>;
 return <><a href="#/comps">← 全部阵容</a><h1>{c.name}</h1><p>{archetypeNames[c.archetype]} · Set {c.set}</p><section className="t-section"><h2>各来源评价</h2>{c.sources.map(s=><SourceLine key={s.source+s.sourceRecordId+s.patch} s={s} detail/>)}</section>{unitList('来源棋盘 / 核心英雄',c.coreUnits)}{unitList('主C',c.carries)}{unitList('主坦',c.tanks)}<section className="t-section"><h2>棋盘涉及羁绊</h2><p>{c.traits.map(t=>traits.get(t)??t).join(' / ')||'暂无明确数据'}</p><small>仅列来源棋盘包含的羁绊，不推断实际激活档位。</small></section><p className="t-muted">归一化时间 {fmt(c.updatedAt)} · 别名 {c.aliases.join(' / ')}</p></>;
}
function Home(){const comps=data.comps.filter(c=>c.sources.some(s=>s.patch===data.metadata.patch&&!s.retained));const summary=data.patch.summary;return <><section className="t-version"><h1>Set {data.metadata.set} <span>· Patch {data.metadata.patch}</span></h1><p>官方更新 {fmt(data.patch.releasedAt)} · <a href={data.patch.officialUrl} target="_blank" rel="noreferrer">公告 ↗</a></p><p>数据更新 {ago(data.metadata.generatedAt)} <span title={data.metadata.generatedAt}>· {fmt(data.metadata.generatedAt)}</span></p></section><section className="t-changes"><div className="t-between"><h2>版本变化</h2><a href={data.patch.officialUrl} target="_blank" rel="noreferrer">官方原文 ↗</a></div>{summary?<><div className="t-change-columns"><p><b>↑ Buff</b>{summary.buffs[0]}</p><p><b>↓ Nerf</b>{summary.nerfs[0]}</p></div><details><summary>更多改动 · 系统与装备</summary>{Object.entries(summary).map(([key,lines])=><div key={key}><h3>{{buffs:'增强',nerfs:'削弱',systemChanges:'系统',otherChanges:'其他'}[key]}</h3><ul>{lines.map(l=><li key={l}>{l}</li>)}</ul></div>)}<small>{data.patch.summaryStatus} · 审核 {fmt(data.patch.summaryReviewedAt)}</small></details></>:<p>{data.patch.summaryStatus}</p>}</section><div className="t-between t-section-title"><h2>META <small>{comps.length} 套</small></h2><a href="#/comps">查看全部 →</a></div>{comps.slice(0,4).map(c=><CompRow key={c.id} comp={c}/>)}{!comps.length&&<p className="t-empty">当前版本尚无已采集阵容。可在阵容页查看保留的历史记录。</p>}<section className="t-section"><h2>Meta 趋势</h2><p>保留来源原始均排变化，不合并为综合涨跌。</p>{comps.flatMap(c=>c.sources.filter(s=>s.trendDelta!==undefined&&s.patch===data.metadata.patch).map(s=>({c,s}))).slice(0,4).map(({c,s})=><div className="t-trend" key={c.id+s.source}><a href={`#/comps/${c.id}`}>{c.name}</a><span>{s.trendDelta!>0?'+':''}{s.trendDelta!.toFixed(3)}</span><small>{sourceNames[s.source]} · {s.patch}</small></div>)}</section><div className="t-between t-section-title"><h2>数据源</h2><a href="#/sources">查看详情 →</a></div>{data.sourceStatus.map(s=><div className="t-source-compact" key={s.id}><span>{s.name}</span><span>{s.detectedPatch??'版本未知'}</span><Badge status={s.status==='error'?'error':sourceFreshness(s.detectedPatch,data.metadata.patch,s.collectedAt,Date.now(),s.sourceUpdatedAt)}/></div>)}</>;}
export function TerminalPage(){const cacheState=useCacheState();const[route,setRoute]=useState(location.hash.slice(1)||'/');const[online,setOnline]=useState(navigator.onLine);const[cacheFailed,setCacheFailed]=useState(false);const[,tick]=useState(0);useEffect(()=>{const change=()=>{setRoute(location.hash.slice(1)||'/');window.scrollTo(0,0);};const net=()=>setOnline(navigator.onLine);const cacheError=()=>setCacheFailed(true);window.addEventListener('tft-cache-unavailable',cacheError);window.addEventListener('hashchange',change);window.addEventListener('online',net);window.addEventListener('offline',net);const timer=setInterval(()=>tick(n=>n+1),60000);return()=>{window.removeEventListener('tft-cache-unavailable',cacheError);window.removeEventListener('hashchange',change);window.removeEventListener('online',net);window.removeEventListener('offline',net);clearInterval(timer);};},[]);
 const nav=[['/','首页','◫'],['/comps','阵容','▤'],['/augments','海克斯','◇'],['/items','装备','▣'],['/sources','数据源','◎']];
 return <div className="terminal"><header className="t-header"><a href="#/">TFT <b>DATA</b></a><span>版本数据终端</span></header><main className="t-main">{(cacheState==="updateAvailable"||cacheState==="updating")&&<div className="t-offline" role="status"><p>{cacheLabels[cacheState]}</p><button className="t-more" disabled={cacheState==="updating"} onClick={applyCacheUpdate}>更新并重新加载</button></div>}{cacheFailed&&<p role="status" className="t-offline">浏览器未能启用离线缓存，断网时可能无法恢复页面。</p>}{!online&&<p role="status" className="t-offline">当前离线，显示上次加载的快照 · {fmt(data.metadata.generatedAt)}</p>}{Date.now()-Date.parse(data.metadata.generatedAt)>24*3600000&&<p className="t-offline">此快照已超过24小时，请核对各来源更新时间。</p>}{route==='/'?<Home/>:route==='/comps'?<CompList/>:route.startsWith('/comps/')?<Detail id={route.split('/')[2]}/>:route==='/augments'?<Catalog key="augments" kind="augments"/>:route==='/items'?<Catalog key="items" kind="items"/>:route==='/sources'?<><h1>数据源状态</h1><p className="t-muted">以 Riot Patch {data.metadata.patch} 为基准。版本一致且采集/来源生成未超过24小时才显示已同步；检查时间不等于内容更新时间。</p>{data.sourceStatus.map(s=><SourceRow key={s.id} s={s}/>)}<section className="t-section"><h2>添加到手机主屏幕</h2><p>部署到 HTTPS 后，在浏览器菜单选择「安装应用」或「添加到主屏幕」。iPhone 使用 Safari 分享菜单。</p><p>缓存就绪后可保留本次完整页面与数据；发现新版本会提示「更新并重新加载」。真实手机断网重开仍待验收。</p></section></>:<><h1>页面不存在</h1><a href="#/">返回首页</a></>}<footer className="t-footer"><span role="status">{cacheLabels[cacheState]}</span><br/>来源独立展示 · 不计算综合评级<br/>快照 {fmt(data.metadata.generatedAt)}</footer></main><nav className="t-nav" aria-label="主导航">{nav.map(([path,label,icon])=><a href={`#${path}`} key={path} aria-current={(path==='/'?route==='/':route.startsWith(path))?'page':undefined}><span aria-hidden="true">{icon}</span>{label}</a>)}</nav></div>;
}

